services:
  hidrate-mqtt-bridge:
    build: .
    image: hidrate-mqtt-bridge:dev
    container_name: hidrate-mqtt-bridge
    network_mode: host
    cap_add:
      - NET_ADMIN
      - NET_RAW
    security_opt:
      - apparmor=unconfined
    volumes:
      - ./config:/config
      - /var/run/dbus:/var/run/dbus
    restart: unless-stopped
    environment:
      - CONFIG_PATH=/config/config.yaml
      - WEB_PORT=8080
      - TZ=Australia/Melbourne
